---
- name: download backup
  command: duplicity restore sftp://vps-jp/srv/backup ~/backup
    creates=~/backup

- name: restore files
  copy:
    src: ~/backup{{ ansible_env.HOME }}/{{ item }}
    dest: ~/{{ item }}
    mode: 'go-rwx'
    backup: yes
  with_items:
    - .vpn/
    - .sesame/
    - .ssh/
    - .gnupg/
    - .purple/accounts.xml
    - .purple/blist.xml
    - .znc/

- name: import VPNs
  command: nmcli connection import type openvpn file "{{ item }}"
  with_items:
    - ~/.sesame/us-nobuto.conf
    - ~/.sesame/us-nobuto-tcp443.conf
    - ~/.sesame/us-nobuto-tcp443-global.conf
