---
- name: restore files at home
  copy:
    src: "{{ item }}"
    dest: ~/
    mode: "go-rwx"
    backup: yes
  with_fileglob:
    - "~/backup{{ ansible_env.HOME }}/*"

- name: restore some dot directories
  copy:
    src: ~/backup{{ ansible_env.HOME }}/{{ item }}
    dest: ~/{{ item }}
    mode: 'go-rwx'
    backup: yes
  with_items:
    #- .vpn/
    - .sesame/
    - .ssh/
    - .gnupg/
