alias C='LC_MESSAGES=C'
alias cdtemp='cd $(mktemp -d)'
alias check-connectivity='httping -sGb -c5 -t5 www.google.co.jp | ccze -A'
alias xclips='xclip -selection clip'
alias xclips-indent='xclips -o | sed -e "s/^/    /" | xclips'
alias xclips-blockquote='xclips -o | sed -e "s/^/> /" | xclips'
alias encmount-canonical='encfs ~/Dropbox/Canonical/ ~/Canonical/'
alias encumount-canonical='fusermount -u ~/Canonical/'
alias encmount-private='encfs ~/Dropbox/private/ ~/Documents/private/'
alias encumount-private='fusermount -u ~/Documents/private/'
alias proxy-ctail='ssh -t 10.0.7.2 sudo tail -F /var/log/squid-deb-proxy/access.log | ccze -A'
alias vpn-canonical='sudo openvpn ~/.sesame/us-nobuto.conf'
alias vpn-canonical-global='sudo openvpn ~/.sesame/us-nobuto-global.conf'
