alias C='LC_MESSAGES=C'
alias cdtemp='cd $(mktemp -d)'
alias check-connectivity='httping -sGb -c5 -t5 www.google.co.jp'
alias xclips='xclip -selection clip'
alias xclips-indent='xclips -o | sed -e "s/^/    /" | xclips'
alias xclips-blockquote='xclips -o | sed -e "s/^/> /" | xclips'
alias encmount-canonical='encfs ~/Dropbox/Canonical/ ~/Canonical/'
alias encumount-canonical='fusermount -u ~/Canonical/'
alias encmount-private='encfs ~/Dropbox/private/ ~/Documents/private/'
alias encumount-private='fusermount -u ~/Documents/private/'
