#cloud-config
output: {all: '| tee -a /var/log/cloud-init-output.log'}
manage_etc_hosts: localhost
password: ubuntu
chpasswd: { expire: false; }

apt_upgrade: true
package_reboot_if_required: true
packages:
  - anacron
  - etckeeper
  - squid-deb-proxy
ssh_authorized_keys:
  - {{ ssh_key }}
debconf_selections: |
  squid-deb-proxy squid-deb-proxy/ppa-enable boolean true
  unattended-upgrades unattended-upgrades/enable_auto_updates boolean true
runcmd:
  - dpkg-reconfigure -fnoninteractive unattended-upgrades
  - dpkg-query -W linux-* | egrep 'linux-(generic|headers|image|signed)' | cut -f1 | xargs apt-get purge -y
  - echo manual > /etc/init/squid3.override
  - echo maas.ubuntu.com > /etc/squid-deb-proxy/mirror-dstdomain.acl.d/20-maas
  - |
      cat >> /etc/squid-deb-proxy/squid-deb-proxy.conf <<"EOF"
      
      # maas.ubuntu.com
      refresh_pattern sjson$ 0 0% 0
      refresh_pattern current\/grubnetx64\.efi\.signed$ 129600 0% 129600
      refresh_pattern root-image\.gz$ 129600 100% 129600
      refresh_pattern \/(boot|di)-kernel$ 129600 100% 129600
      refresh_pattern \/(boot|di)-initrd$ 129600 100% 129600
      
      negative_ttl 20 minutes
      EOF
  - service squid-deb-proxy restart
