---
- hosts: localhost

  roles:
    # hardware specific
    - { role: fmvs90tb, when: "ansible_product_name == 'FMVS90TB'" }

    - common
    - user

    - { role: restore, tags: restore }

    # laptop specific
    - { role: laptop, when: "ansible_form_factor == 'Notebook'" }
