---
- hosts: localhost

  roles:
    - common
    - user

    - role: restore
      tags: restore

    # laptop specific
    - role: laptop
      when: "ansible_form_factor == 'Notebook'"

    # hardware specific
    - role: hardware_t480
      when: "ansible_product_version == 'ThinkPad T480'"
