---
- hosts: localhost

  roles:
    - common
    - user

    - role: restore
      tags: restore

    # laptop specific
    - role: laptop
      when: "ansible_form_factor == 'Notebook'"

    # hardware specific
    - role: laptop_fmvs90tb
      when: "ansible_product_name == 'FMVS90TB'"

    - role: t14gen3amd
      when: "ansible_product_name == '21CFCTO1WW'"
