---
- hosts: localhost

  roles:
    - common
    - user

    - role: restore
      tags: restore

    # laptop specific
    - role: laptop
      when: "ansible_form_factor == 'Notebook'"

    # hardware specific
    - role: laptop_fmvs90tb
      when: "ansible_product_name == 'FMVS90TB'"

    - role: laptop_t14gen3amd
      when: "ansible_product_name == '21CF21CFT1'"

    - role: laptop_t14gen5amd
      when: "ansible_product_name == '21MCCTO1WW'"
