---
- name: generate ssh key
  command: ssh-keygen -N '' -f ~/.ssh/id_rsa
    creates=~/.ssh/id_rsa.pub

- name: create ssh controlmasters directory
  file: path=~/.ssh/controlmasters state=directory mode=0700

- name: make XDG directories
  file: path={{ item }} state=directory
  with_items:
    - ~/Documents/Music
    - ~/Documents/Pictures
    - ~/Documents/Videos
  register: xdg_dir

- name: clean up old XDG directories
  command: rmdir "{{ item }}"
  with_items:
    - ~/Music
    - ~/Pictures
    - ~/Videos
  when: xdg_dir|changed

- name: clean up example link
  file: path=~/examples.desktop state=absent
  when: xdg_dir|changed

- name: clear gtk bookmarks
  file: path=~/.config/gtk-3.0/bookmarks state=absent
  when: xdg_dir|changed

- name: create dev directory
  file: path=~/dev state=directory

- name: copy dotfiles
  copy:
    src=files/dotfiles/
    dest=~/
  register: dotfiles

- name: generate ICC profile
  command: |
    cd-create-profile \
      --output ~/.local/share/icc/Gamma.icc \
      ~/.local/share/icc/Gamma.xml
  when: dotfiles|changed

- name: create autostart directory
  file: path=~/.config/autostart state=directory

- name: enable autostart of indicator-multiload
  copy:
    src=/usr/share/applications/indicator-multiload.desktop
    dest=~/.config/autostart/indicator-multiload.desktop

- name: unset LC_*
  lineinfile:
    dest=~/.bashrc
    regexp='^unset \$\{'
    line='unset ${!LC_*}'
    state=present

- name: DEBFULLNAME
  lineinfile:
    dest=~/.bashrc
    regexp='^export DEBFULLNAME='
    line="export DEBFULLNAME='{{ debfullname }}'"
    state=present
  when: "debfullname != ''"

- name: DEBEMAIL
  lineinfile:
    dest=~/.bashrc
    regexp='^export DEBEMAIL='
    line="export DEBEMAIL='{{ debemail }}'"
    state=present
  when: "debemail != ''"

- name: LESS
  lineinfile:
    dest=~/.bashrc
    regexp='^export LESS='
    line="export LESS='-j4'"
    state=present

- name: git PS1
  blockinfile:
    dest: ~/.bashrc
    block: |
      GIT_PS1_SHOWDIRTYSTATE=true
      GIT_PS1_SHOWSTASHSTATE=true
      GIT_PS1_SHOWUNTRACKEDFILES=true
      GIT_PS1_SHOWUPSTREAM='auto'
      GIT_PS1_SHOWCOLORHINTS=true
      GIT_PS1_BASE="${PS1%\\* }"
      __show_exit_status() {
          local exit=$?
          [ "$exit" = 0 ] || printf '\[\e[7m\]%d\[\e[0m\] ' "$exit"
      }
      PROMPT_COMMAND='__git_ps1 "$(__show_exit_status)$GIT_PS1_BASE" "\\\$ "'
- name: git username
  ini_file:
    dest=~/.gitconfig
    section=user
    option=name
    value={{ debfullname }}
    state=present
  when: "debfullname != ''"

- name: git email
  ini_file:
    dest=~/.gitconfig
    section=user
    option=email
    value={{ debemail }}
    state=present
  when: "debemail != ''"

- name: git push.default
  ini_file:
    dest=~/.gitconfig
    section=push
    option=default
    value=simple
    state=present

- name: bzr create directory
  file: path=~/.bazaar state=directory

- name: bzr whoami
  ini_file:
    dest=~/.bazaar/bazaar.conf
    section=DEFAULT
    option=email
    value="{{ debfullname }} <{{ debemail }}>"
    state=present
  when: "debfullname != '' and debemail != ''"

- name: bzr lp-login
  ini_file:
    dest=~/.bazaar/bazaar.conf
    section=DEFAULT
    option=launchpad_username
    value={{ launchpad_username }}
    state=present
  when: "launchpad_username != ''"

- name: bzr diff alias
  ini_file:
    dest=~/.bazaar/bazaar.conf
    section=ALIASES
    option=diff
    value='diff --diff-options="-p"'
    state=present

- name: bzr cdiff alias
  ini_file:
    dest=~/.bazaar/bazaar.conf
    section=ALIASES
    option=cdiff
    value='cdiff --diff-options="-p" --check-style'
    state=present

- name: render dconf
  template:
    src=templates/dconf.ini.j2
    dest=~/.config/dconf/user.ini
  register: dconf

- name: reset dconf
  command: dconf reset -f /
  when: dconf|changed

- name: pause to prevent dconf race conditions
  pause: seconds=5
  when: dconf|changed

- name: import dconf
  shell: dconf load / < ~/.config/dconf/user.ini
  when: dconf|changed

- name: 'workaround for LP: #1422290 - UNZIP'
  lineinfile:
    dest=~/.profile
    regexp="^export {{ item }}="
    line="export {{ item }}='-O CP932 -I CP932'"
    state=present
  with_items:
    - UNZIP
    - ZIPINFO
