---
- name: restrict home access
  file:
    path: "{{ ansible_env.HOME }}"
    mode: 'o-rwx'
  tags: [minimal]

- name: generate ssh key
  user:
    name: "{{ ansible_env.USER }}"
    generate_ssh_key: yes
    ssh_key_comment: "{{ ansible_env.USER }}-default@{{ ansible_hostname }}"
  tags: [minimal]

- name: create ssh controlmasters directory
  file: path=~/.ssh/masters state=directory mode=0700
  tags: [minimal]

- name: make XDG directories
  file: path={{ item }} state=directory
  with_items:
    - ~/Documents/Music
    - ~/Documents/Pictures
    - ~/Documents/Videos
  register: xdg_dir

- name: clean up old XDG directories
  command: rmdir "{{ item }}"
  with_items:
    - ~/Music
    - ~/Pictures
    - ~/Videos
  when: xdg_dir is changed

- name: clean up example link
  file: path=~/examples.desktop state=absent
  when: xdg_dir is changed

- name: clear gtk bookmarks
  file: path=~/.config/gtk-3.0/bookmarks state=absent
  when: xdg_dir is changed

- name: create dev directory
  file: path=~/dev state=directory

- name: copy dotfiles
  copy:
    src=files/dotfiles/
    dest=~/
  register: dotfiles
  tags: [minimal]

- name: make .lessfilter executable
  file: path=~/.lessfilter mode=0755
  tags: [minimal]

- name: generate ICC profile
  command: |
    cd-create-profile \
      --output ~/.local/share/icc/Gamma.icc \
      ~/.local/share/icc/Gamma.xml
  when: dotfiles is changed
  tags: [minimal]

- name: create autostart directory
  file: path=~/.config/autostart state=directory
  tags: [minimal]

- name: enable autostart of indicator-multiload
  copy:
    src=/usr/share/applications/indicator-multiload.desktop
    dest=~/.config/autostart/indicator-multiload.desktop
  tags: [minimal]

- name: DEBFULLNAME
  lineinfile:
    dest=~/.bashrc
    regexp='^export DEBFULLNAME='
    line="export DEBFULLNAME='{{ debfullname }}'"
    state=present
  when: "debfullname != ''"

- name: DEBEMAIL
  lineinfile:
    dest=~/.bashrc
    regexp='^export DEBEMAIL='
    line="export DEBEMAIL='{{ debemail }}'"
    state=present
  when: "debemail != ''"

- name: bashrc
  blockinfile:
    dest: ~/.bashrc
    block: |
      unset ${!LC_*}
      unset LD_PRELOAD

      export LESS='-R -j4'
      export LESS_TERMCAP_md=$'\e[01;38;5;180m'
      export LESS_TERMCAP_me=$'\e[0m'
      export LESS_TERMCAP_ue=$'\e[0m'
      export LESS_TERMCAP_us=$'\e[04;38;5;139m'
      
      [ -r /usr/share/autojump/autojump.sh ] && . /usr/share/autojump/autojump.sh
      [ -r ~/.byobu/prompt ] && . ~/.byobu/prompt
      
      GIT_PS1_SHOWDIRTYSTATE=true
      GIT_PS1_SHOWSTASHSTATE=true
      GIT_PS1_SHOWUNTRACKEDFILES=true
      GIT_PS1_SHOWUPSTREAM='auto'
      GIT_PS1_SHOWCOLORHINTS=true
      GIT_PS1__BASE="${PS1%\$*}"
      GIT_PS1__BASE="${GIT_PS1__BASE%\\}"
      __show_exit_status() {
          local exit=$?
          [ "$exit" = 0 ] || printf '\[\e[7m\]%d\[\e[0m\] ' "$exit"
      }
      PROMPT_COMMAND='__git_ps1 "$(__show_exit_status)$GIT_PS1__BASE" "\$ "'
  tags: [minimal]

- name: git username
  ini_file:
    dest=~/.gitconfig
    section=user
    option=name
    value={{ debfullname }}
    state=present
  when: "debfullname != ''"
  tags: [minimal]

- name: git email
  ini_file:
    dest=~/.gitconfig
    section=user
    option=email
    value={{ debemail }}
    state=present
  when: "debemail != ''"
  tags: [minimal]

- name: git core.pager
  ini_file:
    dest=~/.gitconfig
    section=core
    option=pager
    value="diff-highlight | less -FRX"
    state=present
  tags: [minimal]

- name: git core.autocrlf
  ini_file:
    dest=~/.gitconfig
    section=core
    option=autocrlf
    value=input
    state=present

- name: git diff.renames
  ini_file:
    dest=~/.gitconfig
    section=diff
    option=renames
    value=true
    state=present

- name: git diff.algorithm
  ini_file:
    dest=~/.gitconfig
    section=diff
    option=algorithm
    value=histogram
    state=present

- name: git log.follow
  ini_file:
    dest=~/.gitconfig
    section=log
    option=follow
    value=true
    state=present

- name: render dconf
  template:
    src=templates/dconf.ini.j2
    dest=~/.config/dconf/user.ini
  register: dconf
  tags: [minimal]

- name: reset dconf
  command: dconf reset -f /
  when: dconf is changed
  tags: [minimal]

- name: pause to prevent dconf race conditions
  pause: seconds=5
  when: dconf is changed
  tags: [minimal]

- name: import dconf
  shell: dconf load / < ~/.config/dconf/user.ini
  when: dconf is changed
  tags: [minimal]

- name: 'workaround for LP: #1422290 - UNZIP'
  lineinfile:
    dest=~/.profile
    regexp="^export {{ item }}="
    line="export {{ item }}='-O CP932 -I CP932'"
    state=present
  with_items:
    - UNZIP
    - ZIPINFO

- name: Dropbox disable LAN sync
  command: dropbox lansync n
  changed_when: False
  tags: [minimal]
