---
git_repos:
  - { name: maas, repo: 'https://git.launchpad.net/maas' }
  - { name: juju, repo: 'https://github.com/juju/juju.git' }
  - { name: lxd, repo: 'https://github.com/lxc/lxd.git' }
  - { name: ceph, repo: 'https://github.com/ceph/ceph.git' }
  - { name: kubernetes, repo: 'https://github.com/kubernetes/kubernetes.git' }
  - { name: charm-helpers, repo: 'https://github.com/juju/charm-helpers.git' }
  - { name: openstack-on-lxd, repo: 'https://github.com/openstack-charmers/openstack-on-lxd.git' }
  - { name: openstack-bundles, repo: 'https://github.com/openstack-charmers/openstack-bundles.git' }
  - { name: conjure-up, repo: 'https://github.com/conjure-up/conjure-up.git' }
  - { name: bundle-canonical-kubernetes, repo: 'https://github.com/juju-solutions/bundle-canonical-kubernetes.git' }
