---
- name: 'workaround for LP: #1500504 - i8042.nomux to kernel cmdline'
  copy:
    src=files/lp1500504.cfg
    dest=/etc/default/grub.d/lp1500504.cfg
  become: yes
  register: lp_1500504

- name: 'workaround for LP: #1500504 - update-grub'
  command: update-grub
  become: yes
  when: lp_1500504 is changed

- name: disable IR camera
  copy:
    src: files/99-local-disable-ir-camera.rules
    dest: /etc/udev/rules.d/99-local-disable-ir-camera.rules
  become: yes
