---
- name: force lid-close suspend, otherwise trackpoint will be lost
  blockinfile:
    dest: /etc/systemd/logind.conf
    block: |
      HandleLidSwitch=suspend
      HandleLidSwitchExternalPower=suspend
      HandleLidSwitchDocked=suspend
  become: yes

- name: as above, re-enable user-space lid-close detection
  lineinfile:
    dest: /etc/UPower/UPower.conf
    regexp: '^IgnoreLid='
    line: 'IgnoreLid=false'
    state: present
  become: yes
