---
- name: mkdir grub.d
  file:
    path: /etc/default/grub.d
    state: directory
  become: yes

- name: 21CFCTO1WW - acpi.ec_no_wakeup
  blockinfile:
    path: /etc/default/grub.d/t14_gen3_amd.cfg
    create: yes
    block: |
      # https://gitlab.freedesktop.org/drm/amd/-/issues/1951
      # product: 21CFCTO1WW
      GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT acpi.ec_no_wakeup=1"
  become: yes
  register: t14_gen3_amd

- name: update-grub
  command: update-grub
  become: yes
  when: t14_gen3_amd is changed
