---
- name: install TLP
  apt:
    name: tlp
    install_recommends: no
  become: yes

- name: respect device power status on previous boot
  lineinfile:
    dest: /etc/default/tlp
    regexp: '^RESTORE_DEVICE_STATE_ON_STARTUP='
    line: 'RESTORE_DEVICE_STATE_ON_STARTUP=1'
    state: present
  become: yes
