---
- name: disable lid-close suspend, but lock
  blockinfile:
    dest: /etc/systemd/logind.conf
    block: |
      HandleLidSwitch=lock
      HandleLidSwitchExternalPower=lock
      HandleLidSwitchDocked=ignore
  become: yes

#- name: install TLP
#  apt:
#    name: tlp
#  become: yes
#
#- name: update TLP config
#  copy:
#    src: files/tlp-99-local.conf
#    dest: /etc/tlp.d/99-local.conf
#  become: yes
#
#- name: control wifi.powersave by TLP
#  copy:
#    src: files/default-wifi-powersave-on.conf
#    dest: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
#  become: yes
#
#- name: enable TLP
#  systemd:
#    name: tlp
#    enabled: yes
#  become: yes
