---
- name: disable lid-close suspend, but lock
  blockinfile:
    dest: /etc/systemd/logind.conf
    block: |
      HandleLidSwitch=lock
      HandleLidSwitchExternalPower=lock
      HandleLidSwitchDocked=lock
  become: yes

# https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/111
- name: disable user-space lid-close detection as a workaround
  lineinfile:
    dest: /etc/UPower/UPower.conf
    regexp: '^IgnoreLid='
    line: 'IgnoreLid=true'
    state: present
  become: yes

- name: disable IR camera
  copy:
    src: files/99-local-disable-ir-camera.rules
    dest: /etc/udev/rules.d/99-local-disable-ir-camera.rules
  become: yes

- name: install TLP
  apt:
    name: tlp
  become: yes

- name: update TLP config
  copy:
    src: files/tlp-99-local.conf
    dest: /etc/tlp.d/99-local.conf
  become: yes

- name: control wifi.powersave by TLP
  copy:
    src: files/default-wifi-powersave-on.conf
    dest: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
  become: yes

- name: enable TLP
  systemd:
    name: tlp
    enabled: yes
  become: yes

- name: 'install iwd - LP: #1987252'
  apt:
    name: iwd
  become: yes

- name: 'use iwd - LP: #1987252'
  copy:
    src: files/iwd.conf
    dest: /etc/NetworkManager/conf.d/iwd.conf
  become: yes

- name: mask wpa_supplicant in favor of iwd
  systemd:
    name: wpa_supplicant
    masked: yes
  become: yes
