---
- name: disable lid-close suspend, but lock
  blockinfile:
    dest: /etc/systemd/logind.conf
    block: |
      HandleLidSwitch=lock
      HandleLidSwitchExternalPower=lock
  become: yes

- name: disable IR camera
  copy:
    src: files/99-local-disable-ir-camera.rules
    dest: /etc/udev/rules.d/99-local-disable-ir-camera.rules
  become: yes

- name: install TLP
  apt:
    name: tlp
  become: yes

- name: respect device power status on previous boot
  lineinfile:
    dest: /etc/default/tlp
    regexp: '^RESTORE_DEVICE_STATE_ON_STARTUP='
    line: 'RESTORE_DEVICE_STATE_ON_STARTUP=1'
    state: present
  become: yes
