---
- name: disable lid-close suspend, but lock
  blockinfile:
    dest: /etc/systemd/logind.conf
    block: |
      HandleLidSwitch=lock
      HandleLidSwitchExternalPower=lock
      HandleLidSwitchDocked=ignore
  become: true

- name: custom charging threshold for "Preserve Battery Health"
  copy:
    src: files/61-battery-local.hwdb
    dest: /etc/udev/hwdb.d/61-battery-local.hwdb
  register: custom_charging_threshold
  become: true

- name: load custom charging threshold
  command: systemd-hwdb update
  when: custom_charging_threshold is changed
  changed_when: false
  become: true

- name: enable "Preserve Battery Health"
  copy:
    content: '1'
    dest: /var/lib/upower/charging-threshold-status
  changed_when: false
  become: true

- name: install TLP
  apt:
    name: tlp
  become: true

- name: update TLP config
  copy:
    src: files/tlp-99-local.conf
    dest: /etc/tlp.d/99-local.conf
  become: true

- name: control wifi.powersave by TLP
  copy:
    src: files/default-wifi-powersave-on.conf
    dest: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
  become: true

- name: enable TLP
  systemd:
    name: tlp
    enabled: true
  become: true
