---
- name: disable lid-close suspend, but lock
  blockinfile:
    dest: /etc/systemd/logind.conf
    block: |
      HandleLidSwitch=lock
      HandleLidSwitchExternalPower=lock
  become: yes

- name: disable IR camera
  copy:
    src: files/99-local-disable-ir-camera.rules
    dest: /etc/udev/rules.d/99-local-disable-ir-camera.rules
  become: yes

- name: disable Fire TV mount
  copy:
    src: files/99-local-disable-fire-tv.rules
    dest: /etc/udev/rules.d/99-local-disable-fire-tv.rules
  become: yes

- name: install TLP
  apt:
    name: tlp
  become: yes

- name: update TLP config
  copy:
    src: files/tlp-99-local.conf
    dest: /etc/tlp.d/99-local.conf
  become: yes
