alias ssh='env --unset=LC_CTYPE --unset=LC_PAPER --unset=LC_MEASUREMENT ssh'
alias cdtemp='cd $(mktemp -d)'
alias check-connectivity='httping -sGb -c3 -t5 www.google.co.jp | ccze -A'
alias xclips='xclip -selection clip'
alias xclips-indent='xclips -o | sed -e "s/^/    /" | xclips'
alias xclips-blockquote='xclips -o | sed -e "s/^/> /" | xclips'
alias encmount-canonical='encfs --idle=180 ~/Dropbox/Canonical/ ~/Canonical/'
alias encumount-canonical='fusermount -u ~/Canonical/'
alias encmount-private='encfs --idle=60 ~/Dropbox/private/ ~/Documents/private/'
alias encumount-private='fusermount -u ~/Documents/private/'
alias proxy-ctail='lxc exec squid-deb-proxy -- tail -F /var/log/squid-deb-proxy/access.log | ccze -A'
alias vpn-canonical='sudo openvpn ~/.sesame/us-nobuto.conf'
alias vpn-canonical-global='sudo openvpn ~/.sesame/us-nobuto-global.conf'
