#cloud-config
packages:
  - jq
  - pwgen

write_files:
  - content: |
      [Unit]
      Description=Code Server IDE
      Documentation=https://github.com/cdr/code-server/blob/master/doc/quickstart.md
      After=network.target

      [Service]
      Type=simple
      User=ubuntu
      EnvironmentFile=/home/ubuntu/.code-server
      #WorkingDirectory=/home/ubuntu
      Restart=on-failure
      RestartSec=10

      ExecStart=/usr/local/bin/code-server

      #StandardOutput=append:/var/log/code-server-output.log
      #StandardError=append:/var/log/code-server-error.log

      [Install]
      WantedBy=multi-user.target
    path: /etc/systemd/system/code-server.service

runcmd:
  - wget "$(curl https://api.github.com/repos/cdr/code-server/releases/latest | jq -r .assets[].browser_download_url | grep linux-x86_64)"
  - tar xvf code-server*-linux-x86_64.tar.gz
  - cp -v code-server*-linux-x86_64/code-server /usr/local/bin/
  - echo PASSWORD=$(pwgen -sB 32) | install -o ubuntu -g ubuntu -m 0600 /dev/stdin ~ubuntu/.code-server
  - |
      cat > /home/ubuntu/.local/share/code-server/User/settings.json <<EOF
      {
          "editor.fontFamily": "'Ubuntu Mono', monospace",
          "editor.renderWhitespace": "boundary",
          "editor.cursorStyle": "block",
          "editor.rulers": [
              80,
              100,
              120
          ],
          "editor.scrollBeyondLastLine": false,
          "files.autoSaveDelay": 10000,
          "files.insertFinalNewline": true,
          "files.trimFinalNewlines": true
      }
      EOF
  - |
      sudo -u ubuntu -H code-server \
        --install-extension ms-python.python \
        --install-extension redhat.vscode-yaml \
        --install-extension ms-vscode.Go \
        --install-extension ms-vscode.cpptools
  - systemctl daemon-reload
  - systemctl enable --now code-server.service
