config:
  images.auto_update_interval: "0"
cluster: null
networks:
- config:
    ipv4.address: 10.0.8.1/24
    ipv4.nat: "true"
    ipv4.dhcp.ranges: 10.0.8.51-10.0.8.200
    ipv6.address: none
  description: ""
  managed: true
  name: lxdbr0
  type: ""
storage_pools:
- config:
    source: vgubuntu
    lvm.thinpool_name: LXDThinPool
    volume.block.mount_options: noatime,nobarrier,data=writeback
  description: ""
  name: default
  driver: lvm
profiles:
- config: {}
  description: ""
  devices:
    eth0:
      name: eth0
      nictype: bridged
      parent: lxdbr0
      type: nic
    root:
      path: /
      pool: default
      type: disk
  name: default
