#cloud-config

packages:
  - anacron
  - apache2
  - apt-mirror
  - debmirror
  - simplestreams
  - ccze
  - tree
write_files:
  - content: |
      #!/bin/sh
      sstream-mirror --progress --max=2 \
          --path streams/v1/index.json \
          https://cloud-images.ubuntu.com/releases/ \
          /srv/mirror/cloud-images.ubuntu.com/releases/ \
          arch=amd64 release=xenial \
          'ftype~(lxd.tar.xz|squashfs|root.tar.xz|disk1.img)'
    owner: root:root
    path: /usr/local/bin/sstream-mirror-cloud-images
    permissions: '0755'
  - content: |
      #!/bin/sh
      sstream-mirror --progress --max=2 \
          --keyring=/usr/share/keyrings/ubuntu-cloudimage-keyring.gpg \
          http://images.maas.io/ephemeral-v3/daily/ \
          /srv/mirror/images.maas.io/ephemeral-v3/daily/ \
          arch=amd64 release=xenial
    owner: root:root
    path: /usr/local/bin/sstream-mirror-maas
    permissions: '0755'
  - content: |
      #!/bin/sh
      set -e
      sstream-mirror --progress --max=2 \
          --no-verify \
          --path streams/v1/index2.sjson \
          https://streams.canonical.com/juju/tools/ \
          /srv/mirror/streams.canonical.com/juju/tools/ \
          arch=amd64 release=xenial
      sstream-mirror --progress --max=2 \
          --no-verify \
          https://streams.canonical.com/juju/gui/ \
          /srv/mirror/streams.canonical.com/juju/gui/
    owner: root:root
    path: /usr/local/bin/sstream-mirror-juju
    permissions: '0755'
  - content: |
      $mirrordir='/srv/mirror/archive.ubuntu.com/ubuntu';
      $download_method='http';
      @rsync_extra='none';
      @dists='xenial,xenial-security,xenial-updates,xenial-proposed,xenial-backports';
      @skip_installer='xenial,xenial-security,xenial-updates,xenial-proposed,xenial-backports';
      @sections='main,universe,restricted,multiverse';
      @keyrings='/etc/apt/trusted.gpg';
      @arches='i386,amd64';
      $do_source=1;
      $diff_mode='none';
      @excludes='_i386\.deb$|\.udeb$|\.dsc$|\.tar\.|\.diff\.|/Translation-en_';
      1;
    owner: root:root
    path: /etc/debmirror.conf
    permissions: '0644'
  - content: |
      set nthreads 5
      set mirror_path /srv/mirror
      
      # Ubuntu Cloud Archive
      
      ## xenial-newton
      deb-amd64 http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-updates/newton main
      deb-amd64 http://ubuntu-cloud.archive.canonical.com/ubuntu xenial-proposed/newton main
      
      # PPAs
      
      ## Juju
      deb-amd64 http://ppa.launchpad.net/juju/stable/ubuntu xenial main
      deb-amd64 http://ppa.launchpad.net/juju/proposed/ubuntu xenial main
      deb-amd64 http://ppa.launchpad.net/juju/devel/ubuntu xenial main
      
      ## MAAS
      deb-amd64 http://ppa.launchpad.net/maas/stable/ubuntu xenial main
      deb-amd64 http://ppa.launchpad.net/maas/proposed/ubuntu xenial main
      deb-amd64 http://ppa.launchpad.net/maas/next/ubuntu xenial main
      
      ## Landscape
      deb-amd64 http://ppa.launchpad.net/landscape/16.06/ubuntu xenial main
      
      clean http://ubuntu-cloud.archive.canonical.com/ubuntu
      clean http://ppa.launchpad.net/
    owner: root:root
    path: /etc/apt/mirror.list
    permissions: '0644'
runcmd:
  - rm -rf /var/www/html/
  - ln -s /srv/mirror /var/www/html
