---
- name: disable wakeup events from input devices
  copy:
    src: files/99-local-disable-wakeup-events-from-input-dev.rules
    dest: /etc/udev/rules.d/99-local-disable-wakeup-events-from-input-dev.rules
  become: true

- name: disable Wi-Fi powermanagement with TLP
  copy:
    src: files/99-disable-power-management-for-QCNFA765.conf
    dest: /etc/tlp.d/99-disable-power-management-for-QCNFA765.conf
  become: true

- name: AMDGPU workaround - DC_DISABLE_PSR(0x10)
  copy:
    src=files/amdgpu-workaround.cfg
    dest=/etc/default/grub.d/amdgpu-workaround.cfg
  become: true
  register: t14g5a_amdgpu_workaround

- name: update-grub
  command: update-grub
  become: true
  when: t14g5a_amdgpu_workaround is changed
