---
- name: setup tmpfs
  copy:
    src=/usr/share/systemd/tmp.mount
    dest=/etc/systemd/system/tmp.mount

- name: set swappiness
  sysctl:
    name=vm.swappiness value=1 state=present
    sysctl_file=/etc/sysctl.d/99-local.conf

- name: LVM LXDPool
  lvol: vg=ubuntu-vg lv=LXDPool size=300G opts='--thin'

- name: mirror-content thin LV
  command: lvcreate -T ubuntu-vg/LXDPool -V 300G -n mirror-content
  register: mirror_content_thin
  failed_when: "mirror_content_thin.rc != 0 and 'already exists' not in mirror_content_thin.stderr"

- name: mirror-content thin LV filesystem
  filesystem: fstype=ext4 dev=/dev/ubuntu-vg/mirror-content

- name: fuse allow_other for non-root users
  lineinfile:
    dest=/etc/fuse.conf
    regexp='^user_allow_other'
    line='user_allow_other'
    state=present
