---
- name: make sure the user is in lxd group
  user:
    name: '{{ ansible_user_id }}'
    groups: lxd
    append: yes

- name: check lxd config status
  command: lxc network show lxdbr0
  changed_when: False
  ignore_errors: True
  register: lxd_config_status

- name: lxd init
  shell: echo "{{ lookup('file', 'files/lxd_preseed.yaml') }}" | lxd init --preseed
  when: lxd_config_status is failed

- name: check squid-deb-proxy
  command: lxc info squid-deb-proxy
  changed_when: False
  ignore_errors: True
  register: squid_deb_proxy

- name: init squid-deb-proxy container
  shell: |
    echo "{{ lookup('file', 'files/squid-deb-proxy_user-data.yml') }}" \
        | lxc init ubuntu:noble \
            --config=boot.autostart=true \
            --config=user.vendor-data="$(printf '#cloud-config\n{}\n')" \
            --config=user.user-data="$(cat -)" \
            squid-deb-proxy
  when: "squid_deb_proxy.rc != 0"

- name: set default profile
  command: lxc profile set default user.vendor-data "{{ lookup('file', 'files/lxd_default_vendor-data.yml') }}"
  when: "squid_deb_proxy.rc != 0"

- name: static leases
  shell: |
    lxc network attach lxdbr0 "{{ item.container }}" eth0 eth0 \
        && lxc config device set "{{ item.container }}" eth0 ipv4.address "{{ item.ipv4 }}" \
        || true
  with_items:
    - { container: squid-deb-proxy, ipv4: 10.0.8.2 }
  changed_when: False
