---
- name: LVM update cache
  command: lvscan --cache
  changed_when: False

- name: LVM LXDThinPool
  lvol: vg=ubuntu-vg lv=LXDThinPool size=300G opts='--thin --discard nopassdown'

- name: mirror-content thin LV
  command: lvcreate -T ubuntu-vg/LXDThinPool -V 300G -n mirror-content
  register: mirror_content_thin
  failed_when: "mirror_content_thin.rc != 0 and 'already exists' not in mirror_content_thin.stderr"
  changed_when: "mirror_content_thin.rc == 0"

- name: mirror-content thin LV filesystem
  filesystem: fstype=ext4 dev=/dev/ubuntu-vg/mirror-content

- name: lxd init
  shell: echo "{{ lookup('file', 'files/lxd_preseed.yaml') }}" | lxd init --preseed
  changed_when: False

- name: ubuntu-minimal
  command: lxc remote add --protocol simplestreams ubuntu-minimal 'https://cloud-images.ubuntu.com/minimal/releases'
  changed_when: False
  ignore_errors: True

- name: lxc alias
  command: lxc alias add ubuntu 'exec @ARGS@ -- sudo --login --user ubuntu'
  changed_when: False
  ignore_errors: True

- name: check squid-deb-proxy
  command: lxc info squid-deb-proxy
  changed_when: False
  ignore_errors: True
  register: squid_deb_proxy

- name: init squid-deb-proxy container
  command: lxc init ubuntu:bionic --config=user.user-data="{{ lookup('file', 'files/squid-deb-proxy_user-data.yml') }}" squid-deb-proxy
  when: "squid_deb_proxy.rc != 0"

- name: set default profile
  command: lxc profile set default user.user-data "{{ lookup('file', 'files/lxd_default_user-data.yml') }}"
  when: "squid_deb_proxy.rc != 0"

- name: check mirror
  command: lxc info mirror
  changed_when: False
  ignore_errors: True
  register: mirror

- name: init mirror container
  command: lxc init ubuntu:bionic --config=user.user-data="{{ lookup('file', 'files/mirror_user-data.yml') }}" mirror
  when: "mirror.rc != 0"

- name: attach LV to mirror container
  command: lxc config device add mirror mirror_disk disk source=/dev/ubuntu-vg/mirror-content path=srv/mirror
  register: attach_lv_mirror
  failed_when: "attach_lv_mirror.rc != 0 and 'already exists' not in attach_lv_mirror.stderr"
  changed_when: "attach_lv_mirror.rc == 0"

#- name: modify LV filesystem permission for mirror container
#  file: path=/var/lib/lxd/devices/mirror/disk.srv-mirror state=directory owner=165536 group=165536 mode=0755

- name: static leases
  shell: |
    lxc network attach lxdbr0 "{{ item.container }}" eth0 eth0 \
        && lxc config device set "{{ item.container }}" eth0 ipv4.address "{{ item.ipv4 }}" \
        || true
  with_items:
    - { container: squid-deb-proxy, ipv4: 10.0.8.2 }
    - { container: mirror, ipv4: 10.0.8.3 }
  changed_when: False

- name: create juju openstack profile
  shell: lxc profile create juju-openstack
  changed_when: False
  ignore_errors: True

- name: import juju openstack profile
  shell: echo "{{ lookup('file', 'files/lxd-juju-profile-openstack.yaml') }}" | lxc profile edit juju-openstack
  changed_when: False

- name: import juju kubernetes profile
  shell: echo "{{ lookup('file', 'files/lxd-juju-profile-kubernetes.yaml') }}" | lxc profile edit juju-kubernetes
  changed_when: False
