---
- name: debconf lxd
  debconf: name=lxd question=lxd/bridge-ipv4 vtype=boolean value=true
  register: lxd_bridge
- debconf: name=lxd question=lxd/bridge-ipv4-address vtype=string value=10.0.8.1
- debconf: name=lxd question=lxd/bridge-ipv4-netmask vtype=string value=24
- debconf: name=lxd question=lxd/bridge-ipv4-dhcp-first vtype=string value=10.0.8.51
- debconf: name=lxd question=lxd/bridge-ipv4-dhcp-last vtype=string value=10.0.8.200
- debconf: name=lxd question=lxd/bridge-ipv4-dhcp-leases vtype=string value=255
- debconf: name=lxd question=lxd/bridge-ipv6 vtype=boolean value=false
- debconf: name=lxd question=lxd/bridge-http-proxy vtype=boolean value=false

- name: clear lxd bridge
  file: path=/etc/default/lxd-bridge state=absent
  when: lxd_bridge|changed

- name: dpkg-reconfigure lxd
  command: dpkg-reconfigure -fnoninteractive lxd
  when: lxd_bridge|changed

- name: create loopback image
  command: truncate -s 32G  /var/lib/lxd/loop.img
  changed_when: False

- name: strict permission
  file: path=/var/lib/lxd/loop.img owner=root group=root mode=0600

- name: create filesystem
  filesystem: dev=/var/lib/lxd/loop.img fstype=ext4

- name: mount filesystem
  mount: src=/var/lib/lxd/loop.img name=/var/lib/lxd/containers fstype=ext4 opts=loop,noatime,nobarrier state=mounted

- name: strict permission
  file: path=/var/lib/lxd/containers owner=root group=root mode=0711

- name: lxd init
  command: lxd init --auto
  when: lxd_bridge|changed
