---
# https://github.com/lxc/lxd/blob/master/doc/production-setup.md
- name: sysctl for lxd
  sysctl:
    name={{ item }} value=1048576 state=present
    sysctl_file=/etc/sysctl.d/99-local.conf
  with_items:
    - fs.inotify.max_queued_events
    - fs.inotify.max_user_instances
    - fs.inotify.max_user_watches

- sysctl:
    name=vm.max_map_count value=262144 state=present
    sysctl_file=/etc/sysctl.d/99-local.conf

- name: debconf lxd
  debconf: name=lxd question=lxd/bridge-ipv4 vtype=boolean value=true
  register: lxd_bridge
- debconf: name=lxd question=lxd/bridge-ipv4-address vtype=string value=10.0.8.1
- debconf: name=lxd question=lxd/bridge-ipv4-netmask vtype=string value=24
- debconf: name=lxd question=lxd/bridge-ipv4-dhcp-first vtype=string value=10.0.8.51
- debconf: name=lxd question=lxd/bridge-ipv4-dhcp-last vtype=string value=10.0.8.200
- debconf: name=lxd question=lxd/bridge-ipv4-dhcp-leases vtype=string value=255
- debconf: name=lxd question=lxd/bridge-ipv6 vtype=boolean value=false
- debconf: name=lxd question=lxd/bridge-dnsmasq vtype=string value=/var/lib/lxd/dnsmasq.lxdbr0.conf
- debconf: name=lxd question=lxd/bridge-http-proxy vtype=boolean value=false

- name: clear lxd bridge
  file: path=/etc/default/lxd-bridge state=absent
  when: lxd_bridge|changed

- name: dpkg-reconfigure lxd
  command: dpkg-reconfigure -fnoninteractive lxd
  when: lxd_bridge|changed

- name: lxd init
  command: lxd init --auto
  when: lxd_bridge|changed

- name: static leases
  copy: content="dhcp-host=squid-deb-proxy,10.0.8.2,336h\ndhcp-host=mirror,10.0.8.3,336h" dest=/var/lib/lxd/dnsmasq.lxdbr0.conf owner=root group=root mode=0644
  register: leases

- name: restart lxd-bridge
  service: name=lxd-bridge state=restarted
  when: leases|changed

- name: set LVM thin pool storage backend
  command: lxc config set storage.lvm_vg_name 'ubuntu-vg'
  changed_when: False

- name: enable jumbo frame
  command: lxc profile device set default eth0 mtu 9000
  changed_when: False

- name: check squid-deb-proxy
  command: lxc info squid-deb-proxy
  changed_when: False
  ignore_errors: True
  register: squid_deb_proxy

- name: launch squid-deb-proxy container
  command: lxc launch ubuntu:xenial --config=user.user-data="{{ lookup('file', 'files/squid-deb-proxy_user-data.yml') }}" squid-deb-proxy
  when: "squid_deb_proxy.rc != 0"

- name: set default profile
  command: lxc profile set default user.user-data "{{ lookup('file', 'files/lxd_default_user-data.yml') }}"
  when: "squid_deb_proxy.rc != 0"

- name: check mirror
  command: lxc info mirror
  changed_when: False
  ignore_errors: True
  register: mirror

- name: launch mirror container
  command: lxc launch ubuntu:xenial --config=user.user-data="{{ lookup('file', 'files/mirror_user-data.yml') }}" mirror
  when: "mirror.rc != 0"

- name: attach LV to mirror container
  command: lxc config device add mirror mirror_disk disk source=/dev/ubuntu-vg/mirror-content path=srv/mirror
  register: attach_lv_mirror
  failed_when: "attach_lv_mirror.rc != 0 and 'already exists' not in attach_lv_mirror.stderr"
  changed_when: "attach_lv_mirror.rc == 0"

- name: modify LV filesystem permission for mirror container
  file: path=/var/lib/lxd/devices/mirror/disk.srv-mirror state=directory owner=165536 group=165536 mode=0755
