---
- include: package_apt.yml
  become: yes

- include: package_config.yml
  become: yes

- include: locale.yml
  become: yes

- include: filesystem.yml
  become: yes

- include: package_third-party.yml
  become: yes

#- include: lxd.yml
#  become: yes

- include: xkeysnail.yml
  become: yes
