---
- name: add Juju stable PPA
  apt_repository: repo='ppa:juju/stable' state=present update_cache=yes
  become: yes

- name: install Juju stable with deb
  apt: name=juju state=present
  become: yes

- name: install Juju beta with snap
  command: snap install --classic --beta juju
  become: yes
  register: install_juju
  failed_when: "install_juju.rc != 0 and 'already installed' not in install_juju.stderr"
  changed_when: "install_juju.rc == 0"

- name: install Charm tools with snap
  command: snap install --classic charm
  become: yes
  register: install_charm
  failed_when: "install_charm.rc != 0 and 'already installed' not in install_charm.stderr"
  changed_when: "install_charm.rc == 0"

- name: install Canonical Livepatch with snap
  command: snap install canonical-livepatch
  become: yes
  register: install_charm
  failed_when: "install_charm.rc != 0 and 'already installed' not in install_charm.stderr"
  changed_when: "install_charm.rc == 0"

- name: add my-tools PPA
  apt_repository: repo='ppa:nobuto/my-tools' state=present update_cache=yes
  become: yes

- name: install indicator-presentation
  apt: name=indicator-presentation state=present
  become: yes

- name: install gnome-sound-recorder-all
  apt: name=gnome-sound-recorder-all state=present
  become: yes

- name: disable auto-update of Google Music uploader
  file: path=/etc/default/google-musicmanager state=touch
  become: yes
  changed_when: False
