---
- name: configure apt-listchanges
  copy:
    src: files/listchanges.conf
    dest: /etc/apt/listchanges.conf

- name: disable unattended-upgrades
  copy:
    src: files/99disable-unattended-upgrades
    dest: /etc/apt/apt.conf.d/99disable-unattended-upgrades

- name: try not to load zfs module
  copy:
    src: files/blacklist-zfs.conf
    dest: /etc/modprobe.d/blacklist-zfs.conf

- name: add the user in i2c group set up by i2c-tools for ddcutil
  user:
    name: '{{ ansible_user_id }}'
    groups: i2c
    append: yes
