---
- name: install snaps
  command: snap install {{ item }}
  register: snaps
  failed_when: "snaps.rc != 0 and 'already installed' not in snaps.stderr"
  changed_when: "snaps.rc == 0 and 'already installed' not in snaps.stderr"
  with_items:
    - juju              --classic --beta
    - juju-wait         --classic
    - charm
    - lxd
    - conjure-up        --classic
    #- microk8s          --classic --beta
    - snapcraft         --classic
    - multipass         --classic --beta
    - openstackclients  --classic --edge
    - vscode            --classic

#- name: stop microk8s
#  command: snap disable microk8s
#  changed_when: False
#  when: snaps is changed

- name: remove some snaps
  command: snap remove {{ item }}
  with_items:
    - gnome-3-26-1604
    - gnome-calculator
    - gnome-characters
    - gnome-logs
    - gnome-system-monitor
  changed_when: False
  ignore_errors: True

- name: add user to lxd group
  user:
    name: "{{ ansible_user_id }}"
    groups: lxd
    append: yes

- name: install xkeysnail
  pip:
    name: xkeysnail
    executable: pip3
    version: 0.1.0

- name: add my-tools PPA
  apt_repository:
    repo: 'ppa:nobuto/my-tools'
    state: present
    update_cache: yes

- name: install indicator-presentation
  apt:
    name: indicator-presentation
    state: present

- name: install gnome-sound-recorder-all
  apt:
    name: gnome-sound-recorder-all
    state: present
