---
- name: disable auto refresh on a metered network
  command: snap set system refresh.metered=hold
  changed_when: False

- name: install snaps
  command: snap install {{ item }}
  register: snap
  changed_when: "snap.rc == 0 and 'is already installed' not in snap.stderr"
  with_items: "{{ snaps }}"

- name: disable multipass gui autostart
  command: multipass set client.gui.autostart=false
  changed_when: false
