---
- name: disable auto refresh on a metered network
  command: snap set system refresh.metered=hold
  changed_when: False

- name: install snaps
  snap:
    name: "{{ item.name }}"
    classic: "{{ item.classic }}"
    channel: "{{ item.channel }}"
  with_items: "{{ snaps }}"

- name: "kdiskmark:removable-media connection"
  command: "snap connect kdiskmark:removable-media"
  changed_when: False
