---
- name: disable auto refresh on a metered network
  command: snap set system refresh.metered=hold
  changed_when: False

- name: enable refresh app awareness
  command: snap set core experimental.refresh-app-awareness=true
  changed_when: False

- name: install snaps
  command: snap install {{ item }}
  register: snap
  changed_when: "snap.rc == 0 and 'is already installed' not in snap.stderr"
  with_items: "{{ snaps }}"
