---
- name: install snaps
  command: snap install {{ item }}
  register: snaps
  failed_when: "snaps.rc != 0 and 'already installed' not in snaps.stderr"
  changed_when: "snaps.rc == 0 and 'already installed' not in snaps.stderr"
  with_items:
    - juju              --classic
    - juju-crashdump    --classic
    - juju-wait         --classic
    - charm             --classic
    - kubectl           --classic
    - snapcraft         --classic
    - multipass         --classic --beta
    - openstackclients  --classic
    - code              --classic

- name: remove some snaps
  command: snap remove {{ item }}
  with_items:
    - gnome-3-26-1604
    - gtk-common-themes
    - gnome-calculator
    - gnome-characters
    - gnome-logs
    - gnome-system-monitor
  changed_when: False
  ignore_errors: True

- name: install xkeysnail
  pip:
    name: xkeysnail
    executable: pip3
    version: 0.2.0
