---
- name: enable -proposed
  lineinfile:
    dest: /etc/apt/sources.list.d/ubuntu.sources
    regexp: "^Suites: .* {{ ansible_distribution_release }}-updates"
    line: 'Suites: {{ ansible_distribution_release }} {{ ansible_distribution_release }}-updates {{ ansible_distribution_release }}-backports {{ ansible_distribution_release }}-proposed'
    state: present

- name: apt update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install eatmydata
  apt:
    name: eatmydata
    state: present

- name: apt dist-upgrade
  apt:
    upgrade: dist
  environment: "{{ eatmydata }}"

- name: debconf nullmailer - empty remotes
  debconf:
    name: nullmailer
    question: nullmailer/relayhost
    value: '#'
    vtype: string

- name: apt install packages
  apt:
    name: "{{ packages }}"
    state: present
  environment: "{{ eatmydata }}"

- name: check language support
  command: check-language-support
  register: language_support
  changed_when: False

- name: install missing language support
  apt:
    name: '{{ language_support.stdout.split() }}'
    state: present
  environment: "{{ eatmydata }}"

- name: check language support - ja
  command: check-language-support -l ja
  register: language_support_ja
  changed_when: False

- name: install missing language support - ja
  apt:
    name: '{{ language_support_ja.stdout.split() }}'
    state: present
  environment: "{{ eatmydata }}"

- name: purge thunderbird
  apt: name=thunderbird state=absent purge=yes
