---
- name: configure apt-listchanges
  copy:
    src: files/listchanges.conf
    dest: /etc/apt/listchanges.conf

- name: make git diff-highlight executable
  copy:
    src: /usr/share/doc/git/contrib/diff-highlight/diff-highlight
    dest: /usr/local/bin/diff-highlight
    mode: '0755'

- name: add the user in i2c group set up by i2c-tools for ddcutil
  user:
    name: '{{ ansible_user_id }}'
    groups: i2c
    append: yes
