---
- name: enable -proposed
  template:
    src=templates/proposed.list.j2
    dest=/etc/apt/sources.list.d/proposed.list

- name: set apt_preferences for -proposed
  copy:
    src=files/proposed
    dest=/etc/apt/preferences.d/proposed

- name: apt update
  apt: update_cache=yes cache_valid_time=3600

- name: install eatmydata
  apt: name=eatmydata state=present

- name: apt dist-upgrade
  apt: upgrade=dist
  environment: "{{ eatmydata }}"

- name: apt install packages
  apt: name={{ item }} state=present
  with_items: "{{ packages }}"
  environment: "{{ eatmydata }}"

- name: disable unattended-upgrades
  apt: name=unattended-upgrades state=absent purge=yes

- name: check language support
  command: check-language-support
  register: language_support
  changed_when: False

- name: install missing language support
  apt: name={{ item }} state=present
  with_items: "{{ language_support.stdout.split() }}"
  environment: "{{ eatmydata }}"

- name: purge thunderbird
  apt: name=thunderbird state=absent purge=yes
