---
- name: install xkeysnail
  pip:
    name: xkeysnail
    executable: pip3
    version: 0.4.0
  environment:
    PIP_BREAK_SYSTEM_PACKAGES: "1"

- name: add vscode apt key
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg

- name: add vscode apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    filename: vscode
    state: present

- name: apt install vscode
  apt:
    name: code
    state: present

- name: download steam
  get_url:
    url: https://repo.steampowered.com/steam/archive/stable/steam_latest.deb
    dest: "{{ ansible_user_dir }}/Downloads/steam_latest.deb"
  register: steam

- name: install steam
  apt:
    deb: "{{ ansible_user_dir }}/Downloads/steam_latest.deb"
  when: steam is changed

- name: download speedtest cli
  get_url:
    url: https://install.speedtest.net/app/cli/ookla-speedtest-1.2.0-linux-x86_64.tgz
    dest: "{{ ansible_user_dir }}/Downloads/ookla-speedtest-linux-x86_64.tgz"
  register: speedtest

- name: make sure speedtest directory exists
  file:
    path: /usr/local/lib/ookla-speedtest
    state: directory

- name: extract speedteset cli
  unarchive:
    src: "{{ ansible_user_dir }}/Downloads/ookla-speedtest-linux-x86_64.tgz"
    dest: /usr/local/lib/ookla-speedtest/
    remote_src: yes
    owner: root
    group: root
  when: speedtest is changed

- name: make speedtest executable
  file:
    src: /usr/local/lib/ookla-speedtest/speedtest
    dest: /usr/local/bin/speedtest
    state: link
