---
- name: install Juju with snap
  command: snap install --devmode --beta juju
  become: yes
  register: install_juju
  failed_when: "install_juju.rc != 0 and 'already installed' not in install_juju.stderr"
  changed_when: "install_juju.rc == 0"

- name: install Charm tools with snap
  command: snap install --edge charm
  become: yes
  register: install_charm
  failed_when: "install_charm.rc != 0 and 'already installed' not in install_charm.stderr"
  changed_when: "install_charm.rc == 0"

- name: add my-tools PPA
  apt_repository: repo='ppa:nobuto/my-tools' state=present update_cache=yes
  become: yes

- name: install indicator-presentation
  apt: name=indicator-presentation state=present
  become: yes

- name: install gnome-sound-recorder-all
  apt: name=gnome-sound-recorder-all state=present
  become: yes

- name: disable auto-update of Google Hangout plugin
  file: path=/etc/default/google-talkplugin state=touch
  become: yes
  changed_when: False

- name: download Google Hangout plugin
  get_url:
    url=https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
    dest={{ ansible_env.HOME }}/Downloads/google-talkplugin_current_amd64.deb

- name: install Google Hangout plugin
  apt: deb={{ ansible_env.HOME }}/Downloads/google-talkplugin_current_amd64.deb
  become: yes
