---
- name: install xkeysnail
  pip:
    name: xkeysnail
    executable: pip3
    version: 0.4.0

- name: add vscode apt key
  apt_key:
    id: BC528686B50D79E339D3721CEB3E94ADBE1229CF
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    keyring: /etc/apt/trusted.gpg.d/vscode.gpg

- name: add vscode apt repository
  apt_repository:
    repo: "deb https://packages.microsoft.com/repos/code stable main"
    state: present

- name: apt install vscode
  apt:
    name: code
    state: present
