---
- name: add indicator-presentation PPA
  apt_repository: repo='ppa:indicator-presentation/ppa' state=present update_cache=yes
  become: yes

- name: install indicator-presentation
  apt: name=indicator-presentation state=present
  become: yes

- name: download Google Hangout plugin
  get_url:
    url=https://dl.google.com/linux/direct/google-talkplugin_current_amd64.deb
    dest={{ ansible_env.HOME }}/Downloads/google-talkplugin_current_amd64.deb

- name: install Google Hangout plugin
  apt: deb={{ ansible_env.HOME }}/Downloads/google-talkplugin_current_amd64.deb
  become: yes

- name: download Google Chrome
  get_url:
    url=https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest={{ ansible_env.HOME }}/Downloads/google-chrome-stable_current_amd64.deb

- name: install Google Chrome
  apt: deb={{ ansible_env.HOME }}/Downloads/google-chrome-stable_current_amd64.deb
  become: yes

- name: keep Firefox as primary browser - gnome-www-browser
  alternatives: name=gnome-www-browser path=/usr/bin/firefox
  become: yes

- name: keep Firefox as primary browser - x-www-browser
  alternatives: name=x-www-browser path=/usr/bin/firefox
  become: yes

- name: download Atom
  get_url:
    url=https://atom.io/download/deb
    dest={{ ansible_env.HOME }}/Downloads/atom-amd64.deb

- name: install Atom
  apt: deb={{ ansible_env.HOME }}/Downloads/atom-amd64.deb
  become: yes
