---
- name: disable wakeup events from input devices
  copy:
    src: files/99-local-disable-wakeup-events-from-input-dev.rules
    dest: /etc/udev/rules.d/99-local-disable-wakeup-events-from-input-dev.rules
  become: yes
