---
eatmydata: { LD_LIBRARY_PATH: /usr/lib/libeatmydata, LD_PRELOAD: libeatmydata.so }

packages:

  - etckeeper

  - intel-microcode

  # unity desktop
  - unity-session
  - notify-osd
  - xserver-xorg-input-synaptics

  # minimal dev
  - packaging-dev
  #- bikeshed
  - git
  - git-review
  - bzr
  - bzrtools
  #- python-pip
  #- python-dev
  #- python-virtualenv
  #- python3-pip
  #- python3-dev
  #- python3-hacking
  #- python3-virtualenv
  - tox
  - shellcheck
  #- snapcraft

  # dev
  ## deb
  #- dh-systemd
  #- dh-apport
  #- dh-golang
  ## indicator-presentation
  #- python3-distutils-extra
  #- python3-nose
  #- python3-dbusmock
  #- xvfb
  ## other
  #- libffi-dev

  # openstack
  #- python-openstackclient
  #- python-ceilometerclient

  # portable mirror
  - simplestreams
  - ubuntu-cloudimage-keyring
  - apt-mirror
  - debmirror

  # encryption
  - encfs
  #- enigmail

  # vpn
  - network-manager-openvpn-gnome
  - network-manager-openconnect-gnome
  - network-manager-vpnc-gnome
  - network-manager-strongswan
  - ike-scan
  #- charon-cmd
  - network-manager-l2tp-gnome
  #- ike

  # virt
  - uvtool
  #- lxd
  - virt-manager
  - ovmf
  - openvswitch-switch

  # doc
  #- pandoc
  #- texlive-latex-recommended
  #- diffpdf

  # fonts
  - fonts-dejavu

  # messenger
  - pidgin
  - pidgin-plugin-pack
  ## no SNI support in xenial yet (from 2.12.0)
  - hexchat
  - hexchat-indicator

  # utils - apt
  - apt-listchanges
  - dlocate
  - ppa-purge

  # utils - terminal
  - colordiff
  - dwdiff
  - ccze
  - python-pygments
  - tree
  - xclip
  - jq
  - pwgen

  # utils - network
  - sshuttle
  - nmap
  - sipcalc
  - ipcalc
  - ipv6calc
  - jnettop
  #- speedometer
  - httping
  - zsync
  - powerwake
  #- stunnel4
  #- proxytunnel
  #- tsocks
  #- proxychains
  - freeipmi-tools
  - w3m

  # utils - indicator
  - indicator-multiload
  - diodon

  # backup
  - duplicity
  - python-gi

  # other
  - ibus-mozc
  - dconf-editor
  - gimp
  - inkscape
  #- graphviz
  - chromium-browser
  - yubikey-personalization-gui
  - gedit-plugins
  - gnome-sound-recorder
  #- sox
  #- gstreamer1.0-libav
  #- gstreamer1.0-vaapi
  - desktop-webmail
  #- byzanz
  #- default-java-plugin
  #- midori
  #- maas-cli

  # storage/filesystem
  - thin-provisioning-tools
  #- xfsprogs
  #- zfsutils-linux
  - exfat-fuse

  # investigation
  - powertop
  #- powerstat
  - sysstat

  # android
  #- android-sdk-platform-tools


  # multiverse
  - nautilus-dropbox
