---
eatmydata: { LD_LIBRARY_PATH: /usr/lib/libeatmydata, LD_PRELOAD: libeatmydata.so }

packages:

  - etckeeper

  # unity desktop
  - unity-session
  - notify-osd
  - xserver-xorg-input-synaptics

  # classic deb
  - gnome-characters

  # xkeysnail
  - python3-xlib
  - python3-evdev

  # minimal dev
  - packaging-dev
  - debian-goodies
  #- bikeshed
  - git
  - git-review
  - bzr
  - bzrtools
  - shellcheck
  - yamllint
  - shunit2
  - tox
  - zeal
  - exuberant-ctags
  - npm
  - libgconf-2-4 # electron
  - python3-doc
  - python3-examples
  - python3-pip
  - python3-flake8
  - python3-hacking
  - python3-yapf
  - python-dev
  - python-flake8
  - python-hacking
  - python-yapf

  # dev
  ## deb
  #- dh-systemd
  #- dh-apport
  #- dh-golang
  ## indicator-presentation
  #- python3-distutils-extra
  #- python3-nose
  #- python3-dbusmock
  #- xvfb
  ## other
  #- libffi-dev

  # portable mirror
  - simplestreams
  - ubuntu-cloudimage-keyring
  - apt-mirror
  - debmirror

  # encryption
  - encfs

  # vpn
  - network-manager-fortisslvpn-gnome
  - network-manager-iodine-gnome
  - network-manager-l2tp-gnome
  - network-manager-openconnect-gnome
  - network-manager-openvpn-gnome
  - network-manager-ssh-gnome
  - network-manager-vpnc-gnome
  - network-manager-strongswan
  - ike-scan
  #- charon-cmd
  #- ike

  # virt
  - uvtool
  - lxd
  - virt-manager
  - ovmf
  - openvswitch-switch
  - docker.io

  # doc
  #- pandoc
  #- texlive-latex-recommended
  #- diffpdf

  # fonts
  - fonts-dejavu

  # messenger
  - pidgin
  - pidgin-plugin-pack
  ## no SNI support in xenial yet (from 2.12.0)
  - hexchat
  - hexchat-indicator

  # utils - apt
  - apt-listchanges
  - dlocate
  - ppa-purge

  # utils - terminal
  - byobu
  - autojump
  - colordiff
  - dwdiff
  - ccze
  - python-pygments
  - tree
  - xclip
  - oathtool
  - jq
  - pwgen

  # utils - network
  - curl
  - sshuttle
  - pdsh
  - nmap
  - sipcalc
  - ipcalc
  - ipv6calc
  - jnettop
  #- speedometer
  - httping
  - zsync
  - powerwake
  #- stunnel4
  #- proxytunnel
  #- tsocks
  #- proxychains
  - freeipmi-tools
  - w3m

  # utils - indicator
  - indicator-multiload
  - diodon

  # backup
  - duplicity
  - python-gi

  # other
  - ibus-mozc
  - dconf-editor
  - gimp
  - inkscape
  #- graphviz
  - chromium-browser
  - yubikey-personalization-gui
  - gedit-plugins
  - gnome-sound-recorder
  #- sox
  #- gstreamer1.0-libav
  #- gstreamer1.0-vaapi
  #- byzanz
  #- default-java-plugin
  #- midori
  #- maas-cli

  # storage/filesystem
  - thin-provisioning-tools
  #- xfsprogs
  #- zfsutils-linux
  - exfat-fuse

  # investigation
  - powertop
  - powerstat
  - sysstat
  - dstat
  - fio
  - iperf3
  - linux-tools-common
  - linux-tools-generic
  - linux-doc

  # android
  #- android-sdk-platform-tools


  # multiverse
  - nautilus-dropbox
