---
eatmydata: { LD_LIBRARY_PATH: /usr/lib/libeatmydata, LD_PRELOAD: libeatmydata.so }

snaps:
  - {name: chromium,            classic: false,   channel: null}
  - {name: zoom-client,         classic: false,   channel: null}
  - {name: lxd,                 classic: false,   channel: null}
  - {name: juju,                classic: false,   channel: null}
  - {name: juju-crashdump,      classic: true,  channel: null}
  - {name: juju-wait,           classic: true,  channel: null}
  - {name: charmcraft,          classic: true,  channel: null}
  - {name: snapcraft,           classic: true,  channel: null}
  - {name: kubectl,             classic: true,  channel: null}
  - {name: openstackclients,    classic: false,   channel: null}
  - {name: cmadison,            classic: false,   channel: null}
  - {name: go,                  classic: true,  channel: null}
  - {name: git-ubuntu,          classic: true,  channel: null}
  - {name: vault,               classic: false,   channel: null}

packages:

  - etckeeper

  # GNOME shell
  - gnome-tweaks
  - gnome-shell-extension-prefs
  - gir1.2-gtop-2.0  # gnome-shell-extension-system-monitor

  # dev - minimal
  - build-essential
  - devscripts
  - ubuntu-dev-tools
  - pbuilder
  - debian-goodies  # dman
  - nullmailer  # not to install other MTA accidentally
  - git
  - git-email
  - git-review
  - gh
  - hub
  - shellcheck
  - universal-ctags
  - libxml2-utils  # xmllint
  - yamllint
  - tox
  - pipx
  - python3-pip
  - python3-flake8
  - black
  - mypy
  - libffi-dev
  - libxml2-dev
  - libxslt1-dev
  - jsonnet
  - cargo

  # dev - docs
  - python3-doc
  - python3-examples
  - linux-doc

  # portable mirror
  - simplestreams
  - ubuntu-cloudimage-keyring
  - apt-mirror
  - debmirror

  # encryption
  - encfs
  - paperkey
  - sq

  # backup
  - deja-dup
  - duplicity

  # vpn
  #- network-manager-fortisslvpn-gnome
  #- network-manager-iodine-gnome
  #- network-manager-l2tp-gnome
  - network-manager-openconnect-gnome
  #- network-manager-vpnc-gnome
  #- network-manager-strongswan
  #- ike-scan
  - wireguard-tools
  - openvpn-systemd-resolved

  # virt
  - uvtool
  - virt-manager

  # doc
  - diffpdf
  - ocrmypdf

  # fonts
  - fonts-dejavu
  - fonts-ipafont

  # utils - apt
  - apt-listchanges
  - apt-file
  - dlocate
  - ppa-purge

  # utils - terminal
  - byobu
  - moreutils  # ts
  - fzf
  - ranger
  - colordiff
  - dwdiff
  - git-delta
  - lnav
  - ccze
  - tree
  - oathtool
  - yq
  - j2cli
  - libxml-xpath-perl
  - pwgen
  - pv
  - ripgrep
  - libsecret-tools
  - asciinema
  - qrencode
  - zbar-tools
  - libarchive-tools  # bsdtar
  - easy-rsa

  # utils - network
  - curl
  - sshuttle
  - nmap
  - sipcalc
  - ipcalc
  - whois
  - httping
  - zsync
  - freeipmi-tools
  - w3m
  - wakeonlan
  - testssl.sh

  # utils - indicator
  - diodon

  # utils - images
  - shotwell
  - gnome-screenshot
  - shutter
  - libimage-exiftool-perl
  - jhead
  - libjpeg-turbo-progs  # exifautotran
  - webp
  - gimp
  - inkscape
  - gnome-color-manager

  # other
  - dconf-editor
  - yubikey-manager
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad
  - v4l-utils
  - gnome-sound-recorder
  - gnome-sushi
  - ddcutil
  - xclip
  - xdotool
  - wmctrl
  - gddrescue
  - tidy
  - meld
  - showtime
  - gnome-power-manager

  # investigation
  - htop
  - btop
  - health-check
  - powertop
  - powerstat
  - nvme-cli
  - sg3-utils
  - smartmontools
  - s-tui
  - intel-gpu-tools
  - nvtop
  - radeontop
  - vainfo
  - tcpflow
  - jnettop
  - iputils-arping
  - ldnsutils
  - wireshark
  - avahi-utils
  - wavemon
  - stress-ng
  - fio
  - iperf
  - iperf3
  - sysprof
  - apparmor-utils
  - squashfs-tools-ng
  - libinput-tools
  - evemu-tools
  - skopeo
  - umoci
  - hyperfine
  - rocm-smi
  - libxrt-utils-npu

  # backward compatibility
  - pulseaudio-utils


  # multiverse
  - nautilus-dropbox
