---
eatmydata: { LD_LIBRARY_PATH: /usr/lib/libeatmydata, LD_PRELOAD: libeatmydata.so }

snaps:
  - {name: chromium,            classic: no,   channel: null}
  - {name: zoom-client,         classic: no,   channel: null}
  - {name: lxd,                 classic: no,   channel: null}
  - {name: juju,                classic: no,   channel: 'latest/stable'}
  - {name: juju-crashdump,      classic: yes,  channel: null}
  - {name: juju-wait,           classic: yes,  channel: null}
  - {name: charm,               classic: yes,  channel: null}
  - {name: charmcraft,          classic: yes,  channel: null}
  - {name: snapcraft,           classic: yes,  channel: null}
  - {name: kubectl,             classic: yes,  channel: null}
  - {name: openstackclients,    classic: no,   channel: null}
  - {name: cmadison,            classic: no,   channel: null}
  - {name: go,                  classic: yes,   channel: null}
  - {name: git-ubuntu,          classic: yes,  channel: null}
  - {name: vault,               classic: no,   channel: null}
  - {name: hugo,                classic: no,   channel: null}

packages:

  - etckeeper

  # GNOME shell
  - gnome-tweaks
  - gnome-shell-extension-prefs
  - gnome-shell-extension-manager
  - gir1.2-gtop-2.0  # gnome-shell-extension-system-monitor

  # xkeysnail deps
  - python3-xlib
  - python3-evdev
  - python3-appdirs

  # dev - minimal
  - packaging-dev  # build-essential, devscripts
  - ubuntu-dev-tools
  - pbuilder
  - debian-goodies  # dman
  - nullmailer  # not to install other MTA accidentally
  - git
  - git-email
  - git-review
  - gh
  - hub
  - shellcheck
  - universal-ctags
  - libxml2-utils  # xmllint
  - yamllint
  - tox
  - pipx
  - python3-pip
  - python3-flake8
  - black
  - mypy
  - libffi-dev
  - libxml2-dev
  - libxslt1-dev

  # dev - docs
  - zeal
  - python3-doc
  - python3-examples
  - linux-doc

  # portable mirror
  - simplestreams
  - ubuntu-cloudimage-keyring
  - apt-mirror
  - debmirror

  # encryption
  - encfs
  - paperkey
  - sq

  # backup
  - deja-dup
  - duplicity

  # vpn
  #- network-manager-fortisslvpn-gnome
  #- network-manager-iodine-gnome
  #- network-manager-l2tp-gnome
  - network-manager-openconnect-gnome
  - network-manager-openvpn-gnome
  #- network-manager-vpnc-gnome
  #- network-manager-strongswan
  #- ike-scan
  - wireguard-tools

  # virt
  - uvtool
  - virt-manager

  # doc
  - diffpdf
  - ocrmypdf

  # fonts
  - fonts-dejavu
  - fonts-ipafont

  # utils - apt
  - apt-listchanges
  - dlocate
  - ppa-purge

  # utils - terminal
  - byobu
  - moreutils
  - fzf
  - ranger
  - colordiff
  - dwdiff
  - git-delta
  - lnav
  - ccze
  - python3-pygments
  - tree
  - oathtool
  - jq
  - yq
  - libxml-xpath-perl
  - pwgen
  - pv
  - ripgrep
  - libsecret-tools

  # utils - network
  - curl
  - sshuttle
  - nmap
  - sipcalc
  - ipcalc
  - whois
  - httping
  - zsync
  - freeipmi-tools
  - w3m
  - wakeonlan

  # utils - indicator
  - diodon

  # utils - images
  - shotwell
  - gnome-screenshot
  - shutter
  - libimage-exiftool-perl
  - jhead
  - libjpeg-turbo-progs  # exifautotran
  - webp
  - gimp
  - inkscape

  # other
  - dconf-editor
  - yubikey-manager
  - yubikey-manager-qt
  - gstreamer1.0-libav
  #- gstreamer1.0-plugins-bad
  - v4l-utils
  - gnome-sound-recorder
  - gnome-sushi
  - ddcutil
  - xclip
  - xdotool
  - wmctrl
  - gddrescue
  - tidy
  - meld

  # investigation
  - htop
  - btop
  - health-check
  - powertop
  - powerstat
  - nvme-cli
  - sg3-utils
  - smartmontools
  - s-tui
  - intel-gpu-tools
  - nvtop
  - radeontop
  - vainfo
  - tcpflow
  - jnettop
  - iputils-arping
  - wireshark
  - wavemon
  - sysstat
  - stress-ng
  - fio
  - iperf
  - iperf3
  - sysprof
  - apparmor-utils

  # backward compatibility
  - pulseaudio-utils


  # multiverse
  - nautilus-dropbox
