---
eatmydata: { LD_LIBRARY_PATH: /usr/lib/libeatmydata, LD_PRELOAD: libeatmydata.so }

snaps:
  - {name: chromium,            classic: no, channel: null}
  - {name: zoom-client,         classic: no, channel: null}
  - {name: lxd,                 classic: no, channel: null}
  - {name: juju,                classic: yes, channel: null}
  - {name: juju-crashdump,      classic: yes, channel: null}
  - {name: juju-wait,           classic: yes, channel: null}
  - {name: charm,               classic: yes, channel: null}
  - {name: charmcraft,          classic: yes, channel: null}
  - {name: snapcraft,           classic: yes, channel: null}
  - {name: kubectl,             classic: yes, channel: null}
  - {name: openstackclients,    classic: no, channel: null}
  - {name: cmadison,            classic: no, channel: null}
  - {name: yq,                  classic: no, channel: null}
  - {name: git-ubuntu,          classic: yes, channel: null}
  - {name: vault,               classic: no, channel: null}
  - {name: hugo,                classic: no, channel: 'extended'}

packages:

  - etckeeper

  # GNOME shell
  - gnome-tweaks
  - gnome-shell-extension-prefs
  - gnome-shell-extension-manager
  - gnome-clocks
  - gir1.2-gtop-2.0  # gnome-shell-extension-system-monitor

  # xkeysnail deps
  - python3-xlib
  - python3-evdev

  # dev - minimal
  - packaging-dev
  - debian-goodies  # dman
  - nullmailer
  - git
  - git-email
  - git-review
  - hub
  - bzr
  - bzrtools
  - bzr-fastimport
  - shellcheck
  - yamllint
  - tox
  - zeal
  - python3-doc
  - python3-examples
  - python3-pip
  - python3-flake8
  - mypy
  - black
  - libffi-dev
  - libxml2-dev
  - libxslt1-dev

  # dev
  #- exuberant-ctags
  #- npm
  #- python3-yapf

  # portable mirror
  - simplestreams
  - ubuntu-cloudimage-keyring
  - apt-mirror
  - debmirror

  # encryption
  - encfs

  # vpn
  #- network-manager-fortisslvpn-gnome
  #- network-manager-iodine-gnome
  #- network-manager-l2tp-gnome
  - network-manager-openconnect-gnome
  - network-manager-openvpn-gnome
  #- network-manager-vpnc-gnome
  #- network-manager-strongswan
  #- ike-scan
  - wireguard-tools

  # virt
  - uvtool
  - virt-manager
  - ovmf

  # doc
  - diffpdf
  - ocrmypdf

  # fonts
  - fonts-dejavu
  - fonts-ipafont

  # utils - apt
  - apt-listchanges
  - dlocate
  - ppa-purge

  # utils - terminal
  - byobu
  - moreutils
  - fzf
  - colordiff
  - dwdiff
  - lnav
  - ccze
  - python3-pygments
  - tree
  - oathtool
  - jq
  - libxml-xpath-perl
  - pwgen
  - pv
  - ripgrep
  - sq
  - paperkey

  # utils - network
  - curl
  - sshuttle
  - nmap
  - tcpflow
  - sipcalc
  - ipcalc
  - whois
  - jnettop
  - httping
  - iputils-arping
  - zsync
  - freeipmi-tools
  - w3m
  - wakeonlan
  - wireshark

  # utils - indicator
  - diodon

  # other
  - gnome-screenshot
  - dconf-editor
  - gimp
  - inkscape
  - yubikey-personalization-gui
  - gstreamer1.0-libav
  - gstreamer1.0-plugins-bad
  - v4l-utils
  - gnome-sound-recorder
  - gnome-sushi
  - ddcutil
  - xclip
  - xdotool
  - wmctrl
  - gddrescue

  # storage/filesystem
  - thin-provisioning-tools

  # investigation
  - htop
  - powertop
  - powerstat
  - nvme-cli
  - intel-gpu-tools
  - vainfo
  - sysstat
  - dstat
  - stress-ng
  - fio
  - iperf
  - iperf3
  - sysprof
  - linux-doc
  - apparmor-utils


  # multiverse
  - nautilus-dropbox
