---
eatmydata: { LD_LIBRARY_PATH: /usr/lib/libeatmydata, LD_PRELOAD: libeatmydata.so }

packages:

  - etckeeper

  # minimal dev
  - packaging-dev
  - bikeshed
  - git
  - git-review
  - bzr
  - bzrtools
  - python-dev
  - python-virtualenv
  - python3-dev
  - python3-hacking
  - python3-virtualenv
  - tox
  - shellcheck

  # dev
  ## deb
  - dh-systemd
  - dh-golang
  ## indicator-presentation
  - python3-distutils-extra
  - python3-nose
  - python3-dbusmock
  - xvfb

  # openstack
  - python-openstackclient
  - python-ceilometerclient

  # encryption
  - encfs
  - enigmail

  # vpn
  - network-manager-openvpn-gnome
  - network-manager-openconnect-gnome

  # virt
  - uvtool
  - lxd
  - virt-manager
  - openvswitch-switch

  # doc
  - pandoc
  - texlive-latex-recommended
  - diffpdf

  # fonts
  - fonts-dejavu

  # messenger
  - pidgin
  - pidgin-plugin-pack
  ## no SNI support in xenial yet (from 2.12.0)
  - hexchat
  - hexchat-indicator

  # utils - apt
  - apt-listchanges
  - dlocate
  - ppa-purge

  # utils - terminal
  - colordiff
  - dwdiff
  - ccze
  - python-pygments
  - tree
  - xclip
  - jq
  - pwgen

  # utils - network
  - sshuttle
  - nmap
  - sipcalc
  - ipcalc
  - ipv6calc
  - jnettop
  - httping
  - zsync
  - powerwake

  # utils - indicator
  - indicator-multiload
  - diodon

  # backup
  - duplicity

  # other
  - ibus-mozc
  - dconf-editor
  - gimp
  - inkscape
  - chromium-browser
  - yubikey-personalization-gui
  - gedit-plugins
  - gnome-sound-recorder
  - sox
  - gstreamer1.0-libav
  - gstreamer1.0-vaapi
  - desktop-webmail
  - byzanz
  - default-java-plugin

  # storage/filesystem
  - thin-provisioning-tools
  - xfsprogs
  - zfsutils-linux

  # investigation
  - powertop
  - powerstat
  - sysstat

  # restricted
  - intel-microcode

  # multiverse
  - nautilus-dropbox
