#!/bin/bash

set -e
set -u

interval=10

# notify < -60dBm situation
# Link quality 49 = -61dBm + 110
# Link quality percent 70% = 49/70
#link_quality_threshold=49
link_quality_threshold=34

wireless=$(cat /proc/net/wireless)
invalid_misc_p=$(echo "$wireless" | grep -m1 ^wl | awk '{print $10}')
retries_p=$(echo "$wireless" | grep -m1 ^wl | awk '{print $9}')

while true; do
    sleep "$interval"
    wireless=$(cat /proc/net/wireless)
    iface=$(echo "$wireless" | grep -m1 ^wl || true)
    invalid_misc=$(echo "$iface" | awk '{print $10}')
    retries=$(echo "$iface" | awk '{print $9}')
    link_quality=$(echo "$iface" | awk '{print $3}' | tr -d .)

    if [ -n "$invalid_misc_p" ] && [ -n "$invalid_misc" ]; then
        count_invalid=$((invalid_misc - invalid_misc_p))
        count_retries=$((retries - retries_p))
        if [ "$count_invalid" -gt 1 ]; then
            notify-send \
                -i network-wireless-hardware-disabled-symbolic \
                -h int:transient:1 \
                'Wireless packet loss detected' \
                "${count_invalid} invalid packets in ${interval}s"

            echo "${count_invalid} invalid packets in ${interval}s" >&2
            echo "$wireless" >&2
        elif [ "$count_retries" -gt 1 ]; then
            notify-send \
                -i network-wireless-hardware-disabled-symbolic \
                -h int:transient:1 \
                'Wireless packet loss detected' \
                "${count_retries} excessive retries in ${interval}s"

            echo "${count_retries} excessive retries in ${interval}s" >&2
            echo "$wireless" >&2
        elif [ "$link_quality" -le "$link_quality_threshold" ]; then
            link_quality_percent=$((link_quality * 100 / 70))
            notify-send \
                -i network-wireless-signal-weak-symbolic \
                -h int:transient:1 \
                'Link quality is low' \
                "${link_quality_percent}%"

            echo "$wireless" >&2
        fi
    fi

    invalid_misc_p="$invalid_misc"
    retries_p="$retries"
done
